# This is a basic workflow to help you get started with Actions

name: mozjs MIPS build

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Checkout mozilla-unified
        uses: actions/checkout@v4
        with:
          repository: mozilla/gecko-dev
          path: './mozilla-unified'

      # Runs a single command using the runners shell
      - name: Bootstrap
        working-directory: ./mozilla-unified
        run: ./mach bootstrap

      # Runs a set of commands using the runners shell
      - name: Build
        working-directory: ./mozilla-unified
        run: ./mach build
